-- Об’єкт «Class» (Клас)
CREATE TABLE Class (
    class_name VARCHAR(10) PRIMARY KEY,
    class_Teacher INT NOT NULL UNIQUE,
    CONSTRAINT class_name_format CHECK (class_name ~ '^(?:[1-9]|1[01])-([А-ЩЬЮЯҐЄІЇ]|[а-щьюяґєії])$')
);

-- Об’єкт «Student» (Учень)
CREATE TABLE Student (
    student_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    student_phone VARCHAR(15) UNIQUE,
    student_email VARCHAR(50) UNIQUE,
    student_surname VARCHAR(50) NOT NULL,
    student_name VARCHAR(50) NOT NULL,
    student_patronymic VARCHAR(50),
    student_Class VARCHAR(10) NOT NULL,
    CONSTRAINT student_phone_format CHECK (student_phone ~ '^0[3-9]\d{1}-\d{3}-\d{4}$'),
    CONSTRAINT student_email_format CHECK (student_email ~ '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'),
    CONSTRAINT fk_student_class FOREIGN KEY (student_Class) REFERENCES Class(class_name)
);

-- Об’єкт «Parent» (Батьки)
CREATE TABLE Parent (
    parent_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    parent_email VARCHAR(50) UNIQUE,
    parent_phone VARCHAR(15) NOT NULL UNIQUE,
    parent_name VARCHAR(50) NOT NULL,
    parent_surname VARCHAR(50) NOT NULL,
    parent_patronymic VARCHAR(50),
    CONSTRAINT parent_email_format CHECK (parent_email ~ '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'),
    CONSTRAINT parent_phone_format CHECK (parent_phone ~ '^0[3-9]\d{1}-\d{3}-\d{4}$')
);

-- Об’єкт «Teacher» (Вчитель)
CREATE TABLE Teacher (
    teacher_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    teacher_email VARCHAR(50) NOT NULL UNIQUE,
    teacher_phone VARCHAR(15) NOT NULL UNIQUE,
    teacher_surname VARCHAR(50) NOT NULL,
    teacher_name VARCHAR(50) NOT NULL,
    teacher_patronymic VARCHAR(50),
    teacher_position VARCHAR(50) NOT NULL,
    CONSTRAINT teacher_email_format CHECK (teacher_email ~ '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'),
    CONSTRAINT teacher_phone_format CHECK (teacher_phone ~ '^0[3-9]\d{1}-\d{3}-\d{4}$')
);

-- Додавання зовнішнього ключа для class_Teacher після створення таблиці Teacher
ALTER TABLE Class
ADD CONSTRAINT fk_class_teacher FOREIGN KEY (class_Teacher) REFERENCES Teacher(teacher_id);

-- Об’єкт «Subject» (Предмет)
CREATE TABLE Subject (
    subject_name VARCHAR(30) PRIMARY KEY,
    subject_desc TEXT UNIQUE
);

-- Об’єкт «Homework» (Домашнє завдання)
CREATE TABLE Homework (
    homework_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    homework_Subject VARCHAR(30) NOT NULL,
    homework_description TEXT NOT NULL UNIQUE,
    homework_date DATE NOT NULL,
    homework_Class VARCHAR(10) NOT NULL,
    CONSTRAINT fk_homework_subject FOREIGN KEY (homework_Subject) REFERENCES Subject(subject_name),
    CONSTRAINT fk_homework_class FOREIGN KEY (homework_Class) REFERENCES Class(class_name),
    CONSTRAINT homework_class_format CHECK (homework_Class ~ '^(?:[1-9]|1[01])-([А-ЩЬЮЯҐЄІЇ]|[а-щьюяґєії])$')
);

-- Об’єкт «Timetable» (Розклад)
CREATE TABLE Timetable (
    time_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    time_Class VARCHAR(10) NOT NULL,
    time_day_of_week VARCHAR(10) NOT NULL,
    time_time TIME NOT NULL,
    time_Subject_name VARCHAR(30) NOT NULL,
    time_Teacher_id INT NOT NULL,
    time_homework_id INT NOT NULL,
    CONSTRAINT fk_time_class FOREIGN KEY (time_Class) REFERENCES Class(class_name),
    CONSTRAINT time_class_format CHECK (time_Class ~ '^(?:[1-9]|1[01])-([А-ЩЬЮЯҐЄІЇ]|[а-щьюяґєії])$'),
    CONSTRAINT time_day_of_week_check CHECK (time_day_of_week IN ('Понеділок', 'Вівторок', 'Середа', 'Четвер', 'П''ятниця')),
    CONSTRAINT fk_time_subject FOREIGN KEY (time_Subject_name) REFERENCES Subject(subject_name),
    CONSTRAINT fk_time_teacher FOREIGN KEY (time_Teacher_id) REFERENCES Teacher(teacher_id),
    CONSTRAINT fk_time_homework FOREIGN KEY (time_homework_id) REFERENCES Homework(homework_id)
);

-- Об’єкт «Journal» (Журнал)
CREATE TYPE journal_status_enum AS ENUM ('Присутній', 'Відсутній', 'Н');

CREATE TABLE Journal (
    journal_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    journal_Student_id INT NOT NULL,
    journal_time_id INT NOT NULL,
    journal_mark SMALLINT,
    journal_note TEXT,
    journal_status journal_status_enum NOT NULL,
    CONSTRAINT fk_journal_student FOREIGN KEY (journal_Student_id) REFERENCES Student(student_id),
    CONSTRAINT fk_journal_time FOREIGN KEY (journal_time_id) REFERENCES Timetable(time_id),
    CONSTRAINT journal_mark_check CHECK (journal_mark >= 1 AND journal_mark <= 12)
);

-- Об’єкт «StudentParent» (Батьки учня)
CREATE TABLE StudentParent (
    student_id_ref INT,
    parent_id_ref INT,
    PRIMARY KEY (student_id_ref, parent_id_ref),
    CONSTRAINT fk_studentparent_student FOREIGN KEY (student_id_ref) REFERENCES Student(student_id),
    CONSTRAINT fk_studentparent_parent FOREIGN KEY (parent_id_ref) REFERENCES Parent(parent_id)
);
